[[pages]]
path = "streamlit_app_web.py"
name = "KPIS de riesgo"

[[pages]]
path = "pages/PnL por analista.py"
name = "PnL por analista"

[[pages]]
path = "pages/Propuesta clusters.py"
name = "Propuesta clusters"
